name: unittest
on: [push, pull_request]
jobs:
  unittest:
    runs-on: ubuntu-latest
    name: Unittest with pytest
    services:
      cassandra:
        image: cassandra
        ports:
          - 9042:9042
    env:
      CASS_DRIVER_NO_CYTHON: 1

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: sleep 70 && docker logs "${{ job.services.cassandra.id }}"
      - run: |
          pip install poetry
          poetry install
      - name: Run test
        run: poetry run pytest
