on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    name: Unittest with pytest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/set-python@v1
      with:
        python-version: '3.x'
    - name: Get the output time
      run: echo "test github actions"
