on: [push]

name: unittest

jobs:

  unittest:
    runs-on: ubuntu-latest
    name: Unittest with pytest
    services:
      cassandra:
        image: cassandra
        ports:
          - 9042:9042
    env:
      CASS_DRIVER_NO_CYTHON: 1

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: |
        pip install poetry
        poetry install
    - name: Run test
      run: poetry run pytest
